# Generated by Django 5.2.8 on 2025-12-03 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.IntegerField(default=0, help_text='Valor entre 0 e 100', verbose_name='Porcentagem de Progresso')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.course', verbose_name='Curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Progresso do Curso',
                'verbose_name_plural': 'Progressos dos Cursos',
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_progress')],
            },
        ),
    ]
