# Generated by Django 5.2.8 on 2025-12-15 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_courseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('points', models.IntegerField(default=0, verbose_name='Pontos')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Categoria')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa')], default='ativa', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Missão',
                'verbose_name_plural': 'Missões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('progress', models.IntegerField(default=0, help_text='Para missões incrementais (ex: 3/5 tarefas)', verbose_name='Progresso')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.mission', verbose_name='Missão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_missions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Progresso de Missão do Usuário',
                'verbose_name_plural': 'Progressos de Missões dos Usuários',
                'ordering': ['-completed_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'mission'), name='unique_user_mission')],
            },
        ),
    ]
