# Generated by Django 5.2.8 on 2025-12-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_game_options_alter_gameprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['game', 'order', '-created_at'], 'verbose_name': 'Missão', 'verbose_name_plural': 'Missões'},
        ),
        migrations.AddField(
            model_name='mission',
            name='icon',
            field=models.CharField(choices=[('play', 'Play'), ('book', 'Livro'), ('quiz', 'Quiz'), ('gamepad', 'Controle')], default='play', max_length=20, verbose_name='Ícone'),
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_type',
            field=models.CharField(choices=[('video', 'Vídeo'), ('reading', 'Leitura'), ('quiz', 'Quiz'), ('game', 'Jogo')], default='video', max_length=20, verbose_name='Tipo de Missão'),
        ),
        migrations.AddField(
            model_name='mission',
            name='order',
            field=models.IntegerField(default=0, help_text='Ordem de exibição na trilha do curso', verbose_name='Ordem na Trilha'),
        ),
    ]
