# Generated by Django 5.2.8 on 2025-12-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_mission_options_mission_icon_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mission',
            unique_together={('game', 'order')},
        ),
    ]
