# Generated by Django 5.2.8 on 2025-12-19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mission_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Geral'), ('course', 'Curso')], default='global', max_length=12, verbose_name='Escopo do ranking')),
                ('total_points', models.IntegerField(default=0, verbose_name='Pontos totais')),
                ('missions_completed', models.IntegerField(default=0, verbose_name='Missões concluídas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='core.game', verbose_name='Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Entrada de Ranking',
                'verbose_name_plural': 'Entradas de Ranking',
                'ordering': ['-total_points', 'user_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(fields=('scope', 'user', 'game'), name='unique_leaderboard_scope_user_game'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['scope', 'game', '-total_points'], name='idx_scope_game_points'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['scope', '-total_points'], name='idx_scope_points'),
        ),
    ]
