# Generated by Django 5.2.8 on 2025-12-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_leaderboard_entry'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaderboardentry',
            name='unique_leaderboard_scope_user_game',
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(
                fields=('scope', 'user'),
                condition=models.Q(('scope', 'global')),
                name='unique_leaderboard_global_user',
            ),
        ),
        migrations.AddConstraint(
            model_name='leaderboardentry',
            constraint=models.UniqueConstraint(
                fields=('scope', 'user', 'game'),
                condition=models.Q(('scope', 'course')),
                name='unique_leaderboard_course_user_game',
            ),
        ),
    ]
