# Generated by Django 5.2.8 on 2025-12-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_user_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cursos/banners/",
                verbose_name="Banner",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="video_url",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cursos/videos/",
                verbose_name="Vídeo",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="image_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="cursos/imagens/",
                verbose_name="Imagem",
            ),
        ),
    ]
