# Generated by Django 5.2.8 on 2025-12-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_game_banner_game_video_url_alter_game_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='content_data',
            field=models.JSONField(blank=True, help_text='Conteúdo específico da missão (vídeo_url, quiz_questions, game_config, etc)', null=True, verbose_name='Dados do Conteúdo'),
        ),
    ]
