# Generated by Django 5.2.8 on 2026-01-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='reset_session_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
