# Generated by Django 5.2.8 on 2026-02-11 20:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_passwordresettoken_reset_session_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(choices=[('course_points', 'Pontos do Curso'), ('perfect_missions', 'Missoes Perfeitas'), ('active_days', 'Dias Ativos')], max_length=32, verbose_name='Criterio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_badge_configs', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_configs', to='core.game', verbose_name='Game')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_badge_configs', to=settings.AUTH_USER_MODEL, verbose_name='Atualizada por')),
            ],
            options={
                'verbose_name': 'Configuracao de Badge',
                'verbose_name_plural': 'Configuracoes de Badge',
                'ordering': ['game_id', 'criterion'],
            },
        ),
        migrations.CreateModel(
            name='BadgeTierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Tier')),
                ('required_value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Necessario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('badge_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_rules', to='core.badgeconfig', verbose_name='Configuracao de Badge')),
            ],
            options={
                'verbose_name': 'Regra por Tier da Badge',
                'verbose_name_plural': 'Regras por Tier da Badge',
                'ordering': ['badge_config_id', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='UserBadgeUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Tier')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Desbloqueada em')),
                ('badge_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unlocks', to='core.badgeconfig', verbose_name='Configuracao de Badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_unlocks', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Desbloqueio de Badge do Usuario',
                'verbose_name_plural': 'Desbloqueios de Badge do Usuario',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='badgeconfig',
            constraint=models.UniqueConstraint(fields=('game', 'criterion'), name='unique_badge_config_game_criterion'),
        ),
        migrations.AddConstraint(
            model_name='badgetierrule',
            constraint=models.UniqueConstraint(fields=('badge_config', 'tier'), name='unique_badge_tier_rule_config_tier'),
        ),
        migrations.AddConstraint(
            model_name='badgetierrule',
            constraint=models.CheckConstraint(condition=models.Q(('tier__gte', 1), ('tier__lte', 5)), name='chk_badge_tier_rule_range'),
        ),
        migrations.AddConstraint(
            model_name='badgetierrule',
            constraint=models.CheckConstraint(condition=models.Q(('required_value__gte', 0)), name='chk_badge_tier_rule_required_positive'),
        ),
        migrations.AddConstraint(
            model_name='userbadgeunlock',
            constraint=models.UniqueConstraint(fields=('user', 'badge_config', 'tier'), name='unique_user_badge_unlock_tier'),
        ),
        migrations.AddConstraint(
            model_name='userbadgeunlock',
            constraint=models.CheckConstraint(condition=models.Q(('tier__gte', 1), ('tier__lte', 5)), name='chk_user_badge_unlock_tier_range'),
        ),
    ]
