# Generated by Django 5.2.8 on 2026-04-08 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_temporary_activated_at_and_activation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome informado')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail informado')),
                ('accepted_temporary_terms', models.BooleanField(default=False, verbose_name='Aceite dos termos temporarios')),
                ('accepted_formal_terms', models.BooleanField(default=False, verbose_name='Aceite do aviso formal')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20, verbose_name='Status da solicitacao')),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da solicitacao')),
                ('request_user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent da solicitacao')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitada em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('provisioned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporary_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuario provisionado')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_temporary_access_requests', to=settings.AUTH_USER_MODEL, verbose_name='Revisada por')),
            ],
            options={
                'db_table': 'core_temporaryaccessrequest',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='idx_tar_email_status'), models.Index(fields=['status', 'requested_at'], name='idx_tar_status_req')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('email',), name='uniq_temp_access_pending_email')],
            },
        ),
    ]
