# Generated by Django 5.2.8 on 2026-04-08 09:10

import re

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


LEGACY_NUMERIC_CODE_RE = re.compile(r"^\d{6}$")


def _hash_legacy_codes(apps, schema_editor):
    password_reset_model = apps.get_model("core", "PasswordResetToken")
    activation_model = apps.get_model("core", "TemporaryAccessActivationToken")

    for model in (password_reset_model, activation_model):
        for token_obj in model.objects.all().only("id", "token"):
            stored_value = str(getattr(token_obj, "token", "") or "")
            if not LEGACY_NUMERIC_CODE_RE.fullmatch(stored_value):
                continue

            token_obj.token = make_password(stored_value)
            token_obj.save(update_fields=["token"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_temporaryaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temporaryaccessactivationtoken',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='temporaryaccessactivationtoken',
            name='token',
            field=models.CharField(max_length=128),
        ),
        migrations.RunPython(_hash_legacy_codes, migrations.RunPython.noop),
    ]
