# Generated by Django 5.2.8 on 2026-04-08 10:05

import hashlib
import re

from django.db import migrations, models


SESSION_TOKEN_DIGEST_RE = re.compile(r"^[0-9a-f]{64}$")


def _hash_legacy_session_tokens(apps, schema_editor):
    password_reset_model = apps.get_model("core", "PasswordResetToken")
    activation_model = apps.get_model("core", "TemporaryAccessActivationToken")

    for model, field_name in (
        (password_reset_model, "reset_session_token"),
        (activation_model, "activation_session_token"),
    ):
        queryset = model.objects.exclude(**{f"{field_name}__isnull": True}).only(
            "id",
            field_name,
        )
        for token_obj in queryset:
            stored_value = str(getattr(token_obj, field_name, "") or "").strip()
            if not stored_value or SESSION_TOKEN_DIGEST_RE.fullmatch(stored_value):
                continue

            setattr(
                token_obj,
                field_name,
                hashlib.sha256(stored_value.encode("utf-8")).hexdigest(),
            )
            token_obj.save(update_fields=[field_name])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_passwordresettoken_failed_attempts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="reset_session_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="temporaryaccessactivationtoken",
            name="activation_session_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(
            _hash_legacy_session_tokens,
            migrations.RunPython.noop,
        ),
    ]
