# Generated by Django 5.2.8 on 2026-04-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_missioncompletions_consumption_validated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioncompletions',
            name='consumption_heartbeat_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de heartbeats de consumo'),
        ),
        migrations.AddField(
            model_name='missioncompletions',
            name='consumption_marked_complete_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consumo marcado como concluido em'),
        ),
        migrations.AddField(
            model_name='missioncompletions',
            name='consumption_progress_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Progresso de consumo em segundos'),
        ),
        migrations.AddField(
            model_name='missioncompletions',
            name='last_consumption_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo heartbeat de consumo em'),
        ),
    ]
