# Generated by Django 5.2.8 on 2026-04-09 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_missioncompletions_consumption_heartbeat_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryaccessrequest',
            name='reviewed_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail que revisou'),
        ),
        migrations.CreateModel(
            name='TemporaryAccessEmailReviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_email', models.EmailField(max_length=254, verbose_name='E-mail do revisor')),
                ('action', models.CharField(choices=[('approve', 'Aprovar'), ('reject', 'Rejeitar')], max_length=20, verbose_name='Acao autorizada')),
                ('token_digest', models.CharField(max_length=64, unique=True, verbose_name='Digest do token')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('is_used', models.BooleanField(default=False, verbose_name='Token usado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado em')),
                ('used_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de uso')),
                ('used_user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent de uso')),
                ('result_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('expired', 'Expirada'), ('already_reviewed', 'Ja revisada'), ('invalidated', 'Invalidada')], default='pending', max_length=32, verbose_name='Resultado')),
                ('result_detail', models.CharField(blank=True, max_length=255, verbose_name='Detalhe do resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_review_tokens', to='core.temporaryaccessrequest', verbose_name='Solicitacao de acesso')),
            ],
            options={
                'db_table': 'core_temporaryaccessemailreviewtoken',
                'indexes': [models.Index(fields=['access_request', 'is_used'], name='idx_taert_request_used'), models.Index(fields=['reviewer_email', 'action'], name='idx_taert_reviewer_action')],
            },
        ),
    ]
