# Generated by Django 5.2.8 on 2026-04-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_temporaryaccessrequest_reviewed_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missioncompletions',
            name='consumption_next_nonce_digest',
            field=models.CharField(blank=True, max_length=64, verbose_name='Digest do proximo nonce de consumo'),
        ),
        migrations.AddField(
            model_name='missioncompletions',
            name='consumption_nonce_issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nonce de consumo emitido em'),
        ),
        migrations.AddField(
            model_name='missioncompletions',
            name='consumption_session_token_digest',
            field=models.CharField(blank=True, max_length=64, verbose_name='Digest do token da sessao de consumo'),
        ),
    ]
